### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [Mocfigh/Projeck-WebDev-1#1]
### Halo Arifia

Kode struktur pada `main` masih kurang tepat, bisa diperbaiki mengikuti contoh struktur dibawah yah:
```html
<main>
 <div id="content">
  <section id="article">
   <article id="">...</article>
   <article id="">...</article>
   ...
  </section>
  <section id="form">...</section>
  ...
 </div>
 <aside>...</aside>
</main>
```

Yang lain udah oke, bisa direvisi lalu upload ulang di repository ini juga, lalu komen dibawah jika sudah upload ulang ya. Terimakasih

**Comment by Mocfigh** [comment]
Kak saya sudah upload revisiannya mohon di crosscheck kembali

**Comment by not-xygen** [comment]
### Halo,
![image](https://github.com/Mocfigh/Projeck-WebDev-1/assets/73971391/b98a8c7e-0dbc-4aba-9c44-390b9510385c)
Bisa dilihat ya `main` masih jauh dari strukturnya:
```html
<main>
 <div id="content">
  <section id="article">
   <article id="">...</article>
   ...
  </section>
  <section id="form">...</section>
  ...
 </div>
 <aside>...</aside>
</main>
```

Bisa direvisi lagi ya lalu komen dibawah, Thanks!

**Comment by Mocfigh** [comment]
Revisi 2 nya sudah saya upload kak.

**Comment by not-xygen** [comment]
Oke Submission Approved. Thanks dan goodluck untuk pembelajaran CSS-nya
